17 02 branch
olgashemet/fast_api pull request #4
Opened 2023-02-19 09:13 UTC by olgashemet

task 2

2023-02-24 03:32 UTC, tgrx requested changes

2023-02-24 03:32 UTC, tgrx commented on Taskfile.yml
> +      - poetry run coverage run -m pytest
А это зачем?)

2023-02-24 03:32 UTC, tgrx commented on Taskfile.yml
> +    dir: "{{.USER_WORKING_DIR}}/algo"
Тут идея в том, чтобы вся папка проверялась, более того - текущая. А такой правкой тсхема сломается. Если ты хочешь проверять только algo, то можешь в консоли в неё зайти и запустить `task run-test`, в этом случае проверка отработает только для твоей папки. Посмотри еще примеры использования на taskfile.dev, может еще удобнее найдешь. А этот файл не меняй плз)

2023-02-24 03:32 UTC, tgrx commented on algo/linkedlist/uni_test.py
> +        ul.__getitem__(-1.5)
Смотри, если магические методы вызывать напрямую, то вся магия исчезает.

`ul[-1.5]` читается более питонячески, чем `ul.__getitem__(-1.5)`, хотя эффективное действие одинаковое

2023-02-25 06:08 UTC, olgashemet commented
Questions:
1)   I ran : poetry run coverage report -m
![Screenshot at Feb 25 07-06-34](https://user-images.githubusercontent.com/88033190/221341602-e4314fcb-e245-4dda-9917-2ce113dda41a.png) What is missing: how do i fix it ?

2023-02-25 18:13 UTC, tgrx commented
> 1. I ran : poetry run coverage report -m
>    ![Screenshot at Feb 25 07-06-34](https://user-images.githubusercontent.com/88033190/221341602-e4314fcb-e245-4dda-9917-2ce113dda41a.png) What is missing: how do i fix it ?

I've updated with commit with enhanced `run-tests-coverage` command. Now it writes the coverage report to the HTML file in any case:

<img width="782" alt="image" src="https://user-images.githubusercontent.com/3865736/221373012-eaebb911-900c-43ce-9024-547aa2c426cf.png">

2023-03-09 18:02 UTC, tgrx approved these changes

2023-03-09 18:02 UTC, merged